import numpy as np

class Continent: 

    def __init__(self):
        self.continent =continent = {           
                'DZ' : 'Africa',
                'AO' : 'Africa',
                'BJ' : 'Africa',
                'BW' : 'Africa',
                'BF' : 'Africa',
                'BI' : 'Africa',
                'CM' : 'Africa',
                'CF' : 'Africa',
                'TD' : 'Africa',
                'KM' : 'Africa',
                'DJ' : 'Africa',
                'EG' : 'Africa',
                'GQ' : 'Africa',
                'ER' : 'Africa',
                'ET' : 'Africa',
                'GA' : 'Africa',
                'GH' : 'Africa',
                'GN' : 'Africa',
                'KE' : 'Africa',
                'LS' : 'Africa',
                'LR' : 'Africa',
                'LY' : 'Africa',
                'MG' : 'Africa',
                'MW' : 'Africa',
                'ML' : 'Africa',
                'MR' : 'Africa',
                'MU' : 'Africa',
                'MA' : 'Africa',
                'MZ' : 'Africa',
                'NE' : 'Africa',
                'NG' : 'Africa',
                'RW' : 'Africa',
                'ST' : 'Africa',
                'SN' : 'Africa',
                'SC' : 'Africa',
                'SL' : 'Africa',
                'SO' : 'Africa',
                'ZA' : 'Africa',
                'SS' : 'Africa',
                'SD' : 'Africa',
                'TZ' : 'Africa',
                'TG' : 'Africa',
                'TN' : 'Africa',
                'UG' : 'Africa',
                'ZM' : 'Africa',
                'ZW' : 'Africa',
                'IO' : 'Africa',
                'CV' : 'Africa',
                'CG' : 'Africa',
                'CD' : 'Africa',
                'CI' : 'Africa',
                'SZ' : 'Africa',
                'TF' : 'Africa',
                'GM' : 'Africa',
                'GW' : 'Africa',
                'YT' : 'Africa',
                'RE' : 'Africa',
                'SH' : 'Africa',
                'EH' : 'Africa',
                'AG' : 'Americas',
                'AR' : 'Americas',
                'BS' : 'Americas',
                'BB' : 'Americas',
                'BZ' : 'Americas',
                'BO' : 'Americas',
                'BR' : 'Americas',
                'CA' : 'Americas',
                'CL' : 'Americas',
                'CO' : 'Americas',
                'CR' : 'Americas',
                'CU' : 'Americas',
                'DM' : 'Americas',
                'DO' : 'Americas',
                'EC' : 'Americas',
                'SV' : 'Americas',
                'GD' : 'Americas',
                'GT' : 'Americas',
                'GY' : 'Americas',
                'HT' : 'Americas',
                'HN' : 'Americas',
                'JM' : 'Americas',
                'MX' : 'Americas',
                'NI' : 'Americas',
                'PA' : 'Americas',
                'PY' : 'Americas',
                'PE' : 'Americas',
                'KN' : 'Americas',
                'LC' : 'Americas',
                'SR' : 'Americas',
                'TT' : 'Americas',
                'US' : 'Americas',
                'UY' : 'Americas',
                'VE' : 'Americas',
                'AI' : 'Americas',
                'AW' : 'Americas',
                'BM' : 'Americas',
                'BQ' : 'Americas',
                'BV' : 'Americas',
                'KY' : 'Americas',
                'CW' : 'Americas',
                'FK' : 'Americas',
                'GF' : 'Americas',
                'GL' : 'Americas',
                'GP' : 'Americas',
                'MQ' : 'Americas',
                'MS' : 'Americas',
                'PR' : 'Americas',
                'BL' : 'Americas',
                'MF' : 'Americas',
                'PM' : 'Americas',
                'VC' : 'Americas',
                'SX' : 'Americas',
                'GS' : 'Americas',
                'TC' : 'Americas',
                'VG' : 'Americas',
                'VI' : 'Americas',
                'AF' : 'Asia',
                'AM' : 'Asia',
                'AZ' : 'Asia',
                'BH' : 'Asia',
                'BD' : 'Asia',
                'BT' : 'Asia',
                'KH' : 'Asia',
                'CN' : 'Asia',
                'CY' : 'Asia',
                'GE' : 'Asia',
                'IN' : 'Asia',
                'ID' : 'Asia',
                'IR' : 'Asia',
                'IQ' : 'Asia',
                'IL' : 'Asia',
                'JP' : 'Asia',
                'JO' : 'Asia',
                'KZ' : 'Asia',
                'KP' : 'Asia',
                'KW' : 'Asia',
                'KG' : 'Asia',
                'LA' : 'Asia',
                'LB' : 'Asia',
                'MY' : 'Asia',
                'MV' : 'Asia',
                'MN' : 'Asia',
                'MM' : 'Asia',
                'NP' : 'Asia',
                'OM' : 'Asia',
                'PK' : 'Asia',
                'PH' : 'Asia',
                'QA' : 'Asia',
                'SA' : 'Asia',
                'SG' : 'Asia',
                'LK' : 'Asia',
                'SY' : 'Asia',
                'TJ' : 'Asia',
                'TH' : 'Asia',
                'TR' : 'Asia',
                'TM' : 'Asia',
                'AE' : 'Asia',
                'UZ' : 'Asia',
                'VN' : 'Asia',
                'YE' : 'Asia',
                'BN' : 'Asia',
                'HK' : 'Asia',
                'KR' : 'Asia',
                'MO' : 'Asia',
                'PS' : 'Asia',
                'TW' : 'Asia',
                'TL' : 'Asia',
                'AL' : 'Europe',
                'AD' : 'Europe',
                'AT' : 'Europe',
                'BY' : 'Europe',
                'BE' : 'Europe',
                'BG' : 'Europe',
                'HR' : 'Europe',
                'CZ' : 'Europe',
                'DK' : 'Europe',
                'EE' : 'Europe',
                'FI' : 'Europe',
                'FR' : 'Europe',
                'DE' : 'Europe',
                'GR' : 'Europe',
                'HU' : 'Europe',
                'IS' : 'Europe',
                'IE' : 'Europe',
                'IT' : 'Europe',
                'LV' : 'Europe',
                'LI' : 'Europe',
                'LT' : 'Europe',
                'LU' : 'Europe',
                'MK' : 'Europe',
                'MT' : 'Europe',
                'MD' : 'Europe',
                'MC' : 'Europe',
                'ME' : 'Europe',
                'NL' : 'Europe',
                'NO' : 'Europe',
                'PL' : 'Europe',
                'PT' : 'Europe',
                'RO' : 'Europe',
                'RU' : 'Europe',
                'SM' : 'Europe',
                'RS' : 'Europe',
                'SK' : 'Europe',
                'SI' : 'Europe',
                'ES' : 'Europe',
                'SE' : 'Europe',
                'CH' : 'Europe',
                'UA' : 'Europe',
                'GB' : 'Europe',
                'AX' : 'Europe',
                'BA' : 'Europe',
                'FO' : 'Europe',
                'GI' : 'Europe',
                'GG' : 'Europe',
                'VA' : 'Europe',
                'IM' : 'Europe',
                'JE' : 'Europe',
                'SJ' : 'Europe',
                'AU' : 'Oceania',
                'FJ' : 'Oceania',
                'KI' : 'Oceania',
                'MH' : 'Oceania',
                'NR' : 'Oceania',
                'NZ' : 'Oceania',
                'PW' : 'Oceania',
                'PG' : 'Oceania',
                'WS' : 'Oceania',
                'SB' : 'Oceania',
                'TO' : 'Oceania',
                'TV' : 'Oceania',
                'VU' : 'Oceania',
                'CK' : 'Oceania',
                'NU' : 'Oceania',
                'AS' : 'Oceania',
                'CX' : 'Oceania',
                'CC' : 'Oceania',
                'PF' : 'Oceania',
                'GU' : 'Oceania',
                'HM' : 'Oceania',
                'FM' : 'Oceania',
                'NC' : 'Oceania',
                'NF' : 'Oceania',
                'MP' : 'Oceania',
                'PN' : 'Oceania',
                'TK' : 'Oceania',
                'UM' : 'Oceania',
                'WF' : 'Oceania',
            }





    def setContinent(self, data):
        #get country attribute
        visitCountries = data["visitor_country"]
        #turn it an array
        arrVC = visitCountries.to_numpy()
        #instianate lists
        result = [] 
        missing = []
        #loop for length
        for i in range(len(arrVC)):
            #try to find its continent in dic and append to result
            try:
                result.append(self.continent[arrVC[i]])
            except:
                #if not in dictionary add a nan value
                missing.append(arrVC[i])
                result.append(np.nan)
                
        #create new attribute using results
        data["Continents"] = result

        return missing





